[0m12:14:05.652384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E7479F750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E747F1710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E747F1F50>]}


============================== 12:14:05.655373 | 41f4c1d9-8d18-4f54-a96e-419dae4c0103 ==============================
[0m12:14:05.655373 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:14:05.656366 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '~/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:14:09.787424 [debug] [MainThread]: Starter project path: C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\include\starter_project
[0m12:14:09.799682 [info ] [MainThread]: 
Your new dbt project "dbtapril2025class" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:14:09.800685 [info ] [MainThread]: Setting up your profile.
[0m12:15:55.375445 [error] [MainThread]: Encountered an error:
[Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'
[0m12:15:55.389462 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\task\init.py", line 166, in create_profile_from_profile_template
    self.write_profile(profile, profile_name)
  File "C:\Users\ctraj\miniconda3\envs\sachinvishaldbtclass\Lib\site-packages\dbt\task\init.py", line 156, in write_profile
    with open(profiles_filepath, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'

[0m12:15:55.392458 [debug] [MainThread]: Command `dbt init` failed at 12:15:55.391463 after 109.84 seconds
[0m12:15:55.392458 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E747D4510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E7479EF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E747F2150>]}
[0m12:15:55.393579 [debug] [MainThread]: Flushing usage events
[0m12:15:55.708974 [debug] [MainThread]: An error was encountered while trying to flush usage events
